
---
# ClusterIssuer `lets-encrypt` の作成
# これは Namespace `cert-manager` には作られない
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: contact@yantene.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
